# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Plutus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Alamofire'
   pod 'SwiftyJSON'
   pod 'SwiftChart'
   pod 'lottie-ios'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'YRPayment'
   pod 'SVProgressHUD'
  # Pods for Plutus

end
